site_name: remoclip
site_description: Local and remote CLI access to your clipboard
site_url: https://remoclip.newmatter.net
repo_url: https://github.com/jeffjjohnston/remoclip
repo_name: GitHub

nav:
  - Home: index.md
  - Video Demo: video.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Server: server.md
  - Client: client.md
  - Release History: releases.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant  # optional, for faster reloads

extra:
  analytics:
    provider: custom

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences