site_name: RemoClip
site_description: Clipboard synchronisation service and CLI documentation
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Server: server.md
  - Client: client.md
theme:
  name: material
markdown_extensions:
  - admonition
  - tables
