site_name: remoclip
site_description: Local and remote CLI access to your clipboard
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Server: server.md
  - Client: client.md
  - Release History: releases.md

theme:
  name: material
  features:
    - navigation.instant  # optional, for faster reloads

repo_url: https://github.com/jeffjjohnston/remoclip
repo_name: GitHub

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences