site_name: remoclip
site_description: Local and remote CLI access to your clipboard
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Server: server.md
  - Client: client.md
theme:
  name: material
markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences